//Question 12

/* The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors? */

import java.util.*;

public class Problem12 {
	
	public static void main(String[] args){
		long start = System.nanoTime();
		Set<Integer> set = new TreeSet<Integer>();
		int first = 0;
		int second = 1;

		while (set.size() < 500){
			set.clear();
		
			first += second;
			second++;
			
			for (int i = 1; i<=(int)Math.sqrt(first); i++){
				if (first % i == 0){
					set.add(i);
					set.add(first/i);
				}
			}
		}
		System.out.println(first);
		System.out.println((System.nanoTime()-start)/1000000000.0 + " seconds");
	}

}
